version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drf-docker-cicd
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    
  jenkins:
        image: jenkins/jenkins:lts
        container_name: jenkins_cicd
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "8080:8080"
        privileged: true
        user: root